name: Cicd for dev env


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build-image:
    runs-on: ubuntu:latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    # - name: Build, tag, deploy docker image
    #   env:
    #     IMAGE_NAME: telemedicine-be
    #     IMAGE_TAG: dev
    #   run: |
    #     echo "${{ secrets.DENNY }}" > .env
    #     cat .env

    - name: Build, tag, deploy docker image
      env:
        IMAGE_NAME: telemedicine-be
        IMAGE_TAG: dev
      run: |
        echo "debug"
        # gradle clean
        # gradle build -x test